### ISSUE TITLE
Outdated version at Hex.pm

### ISSUE THREAD

**Issue by savonarola** [Kabie/dye#3]
Hello!

I have used Dye recently and noted that Hex.pm's version emits warning about unused `mod` variable. This was fixed in 95ba80a4be7bb6cc5c9284f789b67a55403a56c4, but there is no version with this fix at Hex.pm.

Is it possible to push the most recent version of Dye to Hex.pm?

**Comment by Kabie** [comment]
Sorry for the delay, just published a new version.
